#:schema node_modules/wrangler/config-schema.json
name = "ur-automation"
compatibility_date = "2024-08-06"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./apps/web/.vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "ur-automation-db"
database_id = "c1e2bf47-6d4c-4c9d-9c75-894ac6c18925"
preview_database_id = "3f790fd9-c483-4926-be6a-d4469cc1913c"
migrations_dir = "./packages/database/migrations/"
