#:schema node_modules/wrangler/config-schema.json
name = "ur-automation"
compatibility_date = "2024-08-06"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./apps/web/.vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "ur-automation-db"
database_id = "b8e7a950-597d-4ea5-925c-eafb45b42ba9"
migrations_dir = "./packages/database/drizzle/"
